apiVersion: v1
kind: Pod
metadata:
  name: k6-test
  namespace: sa-p5
spec:
  restartPolicy: Never
  containers:
    - name: k6-test
      image: grafana/k6
      command: ["k6", "run", "/scripts/load-test.js"]
      volumeMounts:
        - name: script-vol
          mountPath: /scripts
  volumes:
    - name: script-vol
      configMap:
        name: k6-script
