events {
    worker_connections 1024;
}

http {
    upstream auth {
        server auth-service:4000;
    }
    upstream transaction {
        server transaction-service:4001;
    }
    upstream approval {
        server approval-service:4002;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/transactions {
            proxy_pass http://transaction;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /graphql/transactions {
            proxy_pass http://transaction/graphql;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/approvals {
            proxy_pass http://approval;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /graphql/approvals {
            proxy_pass http://approval/graphql;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
