CARNET="201712620"
REPO_CODE="https://github.com/AndresCalvo98/Pr-cticas-SA-B-201712620"
REPO_GITOPS="https://github.com/AndresCalvo98/software-avanzado-gitops"
APP="sa-platform-app"
NS="argocd"
IMAGE="ghcr.io/andrescalvo98/sa-api-gateway:386a4a07e3c5c4f9f7a4f3bbd91ad3e942f4a1b0"
COSIGN_IDENTITY_REGEXP="https://github.com/AndresCalvo98/Pr-cticas-SA-B-201712620/.*"
COSIGN_ISSUER="https://token.actions.githubusercontent.com"
